services:
  - type: web
    name: swanchatbot
    env: static
    buildCommand: chmod +x node_modules/.bin/react-scripts && npm install && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 